title: Gemini Coder
description: The 2M context AI coding assistant. With emphasis put on context accuracy, Gemini Coder lets you reliably generate the best outputs among all the available tools and avoid over-spent on excessive tokens.
theme: just-the-docs

url: https://robertpiosik.github.io/gemini-coder

aux_links:
  GitHub: https://github.com/robertpiosik/gemini-coder
  Marketplace: https://marketplace.visualstudio.com/items?itemName=robertpiosik.gemini-coder
  Donate: https://buymeacoffee.com/robertpiosik

search_enabled: false

color_scheme: custom

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    color: green
  warning:
    title: Warning
    color: red

aux_links_new_tab: true
